name: Build & Deploy Flutter Web (Pages)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  REPO_NAME: Fitcoach         # <-- your repo name (case-sensitive)
  WORKDIR: fitcoach           # <-- path to the Flutter project folder in the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: flutter pub get

      - name: Build web (release)
        working-directory: ${{ env.WORKDIR }}
        run: flutter build web --release --base-href "/${{ env.REPO_NAME }}/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.WORKDIR }}/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4